### ISSUE TITLE
Ship in nuget?

### ISSUE THREAD

**Issue by user72356** [Tim-Maes/T4Executer#10]
I've asked this question in the VS marketplace but not sure you'll see it there.

How can I ship T4Executer together with a nuget package I'm making? My package contains a T4 template and I need it to run on build on the user machine. I want to avoid having to ask them to install an extension. Thx

**Comment by Tim-Maes** [comment]
Nuget is installed on a project while a VSIX package is installed on the
IDE.

I'll have to research this weekend to see if it's possible to achieve this.
I believe there is a way to tell a Nuget package to go fetch and install an
extension, but I'm not sure how fail-proof this is.

I will keep you posted!



Op do 27 aug. 2020 om 05:17 schreef gb1337 <notifications@github.com>:

**Comment by gb1337** [comment]
Cool thanks. I was thinking something like an external task or executable that can be distributed within a nuget package and configured to be used at build? Admittedly I have never messed around with Tooling, T4, MSBuild, Nuget before so it's a steep learning curve. I see that Mono has a t4 core tool project that can run anywhere, but I couldn't get it to work on a Core 3.x or dotnetstandard 2.x project. Maybe something external to my project would not have these limitations?

**Comment by Tim-Maes** [comment]
I'm afraid there is no clean and solid solution to have this extension shipped in or with a Nuget package. There might be a different approach to achieve this functionailty, but not through this extension.
