### ISSUE TITLE
Can't configure

### ISSUE THREAD

**Issue by Tyri0n** [Tim-Maes/T4Executer#6]
Just installed and I get this when I click configure.

![image](https://user-images.githubusercontent.com/3492775/62137495-f174f000-b2dd-11e9-9f1e-a9376827b753.png)

**Comment by Epsilekt** [comment]
Do you have an open solution with T4 templates inside a project when this error shows?

The latest update resolves issues when trying to configure T4Executer when there are no T4 templates in your solution.

**Comment by Tyri0n** [comment]
I have no T4 templates within the solution. I had uninstalled but just downloaded/installed from within VS2019 again and the same thing happens.

**Comment by Tim-Maes** [comment]
Hello Tyri0n,

Does this issue still occur now?

**Comment by Tyri0n** [comment]
Hi


Is fine now.

 

Cheers

**Comment by Tim-Maes** [comment]
Closing this. Thanks for the reply, Tyri0n.

**Comment by wewedroid** [comment]
I am having the same issue, I just installed it and can't configure on an existing solution with t4 templates.
![image](https://user-images.githubusercontent.com/4475006/131424542-5e5db3f5-b94d-4fb6-92a2-629809a86882.png)

**Comment by Hochmah** [comment]
I have the same issue here!
![image](https://user-images.githubusercontent.com/20425869/132410694-f7d67295-0c0e-4cb2-b315-10c302dc03db.png)
