### ISSUE TITLE
Preserve generated file timestamp when the content is not changed

### ISSUE THREAD

**Issue by zgabi** [Tim-Maes/T4Executer#8]
Is it possible to preserve the timestamp of the generated file (get it before the build and restore after running the template) when the content of the file is not changed?

Our solution contains several quite big projects, and the common project contains a T4 template which is regenerated on every build. => All the projects are rebuilded, which takes much more time than required.

**Comment by zgabi** [comment]
I've created a pull request, could you please check it?

**Comment by Tim-Maes** [comment]
Reviewed and approved.
